### ISSUE TITLE
JSON Schemas do not get generated in some cases

### ISSUE THREAD

**Issue by jeromesimeon** [accordproject/models#22]
A couple of models (`org.isda.cdm.cto` and `patent.cto`) and  fail on JSON schema generation, with the following errors:

```
11:26:07 AM: RangeError: Maximum call stack size exceeded
11:26:08 AM:     at Array.forEach (<anonymous>)
11:26:08 AM:     at JSONSchemaVisitor.visitEnumDeclaration (/opt/build/repo/node_modules/composer-concerto-tools/lib/codegen/fromcto/jsonschema/jsonschemavisitor.js:363:41)
11:26:08 AM:     at JSONSchemaVisitor.visit (/opt/build/repo/node_modules/composer-concerto-tools/lib/codegen/fromcto/jsonschema/jsonschemavisitor.js:58:25)
11:26:08 AM:     at EnumDeclaration.accept (/opt/build/repo/node_modules/composer-concerto/lib/introspect/decorated.js:65:24)
11:26:08 AM:     at JSONSchemaVisitor.visitField (/opt/build/repo/node_modules/composer-concerto-tools/lib/codegen/fromcto/jsonschema/jsonschemavisitor.js:330:31)
11:26:08 AM:     at JSONSchemaVisitor.visit (/opt/build/repo/node_modules/composer-concerto-tools/lib/codegen/fromcto/jsonschema/jsonschemavisitor.js:64:25)
11:26:08 AM:     at Field.accept (/opt/build/repo/node_modules/composer-concerto/lib/introspect/decorated.js:65:24)
11:26:09 AM:     at classDeclaration.getProperties.forEach (/opt/build/repo/node_modules/composer-concerto-tools/lib/codegen/fromcto/jsonschema/jsonschemavisitor.js:250:66)
11:26:09 AM:     at Array.forEach (<anonymous>)
11:26:09 AM:     at JSONSchemaVisitor.visitClassDeclarationCommon (/opt/build/repo/node_modules/composer-concerto-tools/lib/codegen/fromcto/jsonschema/jsonschemavisitor.js:247:42)
```

**Comment by dselman** [comment]
Generating JsonSchema for /Users/dselman/dev/models/build/ergo/monitor: Maximum call stack size exceeded

**Comment by dselman** [comment]
Fixed
